### ISSUE TITLE
The plugin completes code after typing opening curly brace

### ISSUE THREAD

**Issue by acanthite1855** [redhat-developer/intellij-quarkus#1395]
I'm using IDEA Community Edition 2024.2.3 and Quarkus Tools 2.0.2.

Here is how to reproduce it:
1. Make sure that the plugin is installed
2. Create a new quarkus project (keep all setings default)
3. Wait for IDEA to load the project, finish indexing etc - this is important
4. Open a class file
5. Start typing a new method `void test(){`

This is where it breaks IDEA's behavior. After I type `{` it pops up the list of suggestions. IDEA does not do that. And it really ruins user experience, because most of the time after typing `{` you just want to hit **Enter** to move to the next line.

It is also worth mentioning that it reproduces only in quarkus projects. Creating a plain java project will not reproduce it (even with the plugin enabled).

And here is a video of me reproducing it: 

https://github.com/user-attachments/assets/cb146fbc-e1b2-48d0-966a-004a6b68d0af

**Comment by angelozerr** [comment]
Thanks @acanthite1855 for having reported the issue.

I think the problem comes from MicroProfile LS and LSP4IJ.

Let me investigate the problem.

@mrglavas I think you should have the same problem with your Liberty Tools.

**Comment by angelozerr** [comment]
@acanthite1855 it is a very annoying problem. I have fixed this problem but only if your project doesn't contains Qute.

If it is the case and if you want to try this fix before waiting the release:

 * install LSP4IJ 0.7.0 nighty build, see https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds
 * install IJ Quarkus nighty build see https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds

And please give me feedback if it works for you.

I will ping you again when the fix will be available too when your project contains Qute.

**Comment by mrglavas** [comment]
@angelozerr I tried this out with our Liberty Tools 24.0.9 release with a recent LSPIJ 0.7.0 build an couldn't reproduce it. We're still on IntelliJ 2024.1.x if that matters.

**Comment by mrglavas** [comment]
Looks like I reproduced it with the latest LSP4IJ 0.7.0 nightly build. Not sure why I wasn't seeing this before.

![image](https://github.com/user-attachments/assets/3644c6a1-27d4-45c0-bb28-d5e4a29a33e6)

**Comment by angelozerr** [comment]
You should have this problem with any version of LSP4IJ since I have implemented LSP completion triggerCharacters.

There were a bug with this completion triggerCharacters in LSP4IJ 0.7.0 that I have fixed since now you see this auto popup.

And this behavior is correct because it is the MP LS which returns those triggerCharacters.

I did a fix in MP LS and it should work now. For your case you should do nothing, just use last LSP4MP (not released yet) and LSP4IJ 0.7.0 and it should work.

**Comment by mrglavas** [comment]
> I did a fix in MP LS and it should work now. For your case you should do nothing, just use last LSP4MP (not released yet) and LSP4IJ 0.7.0 and it should work.

Thanks. We will try that out.

**Comment by angelozerr** [comment]
@mrglavas if I rememberto have this auto popup, you need to activae this IJ setting

![image](https://github.com/user-attachments/assets/e79a75e4-39a9-42dc-899b-638ea20823d3)

And after that you should see the problem.

**Comment by janheyd-buchner** [comment]
I am still encountering this issue with LSP4IJ 0.7.0, which if I understand the comments above correctly, should have fixed it.

It's very disruptive since I usually immediately press Enter after opening a curly brace. This has now caused me to accidentally commit auto-generated logger fields multiple times.

**Comment by angelozerr** [comment]
You need to install

 * https://github.com/redhat-developer/lsp4ij#testing-nightly-builds
* https://github.com/redhat-developer/intellij-quarkus#testing-nightly-builds

**Comment by janheyd-buchner** [comment]
Thanks for the info, but I am still encountering the issue with
* LSP4IJ 0.7.1-20241027-013436
* Quarkus Tools 2.0.3-20241025-012855

**Comment by angelozerr** [comment]
OK let me see if the nighthy of IJ quarkus  embed the mp language server and qute language server which contains this fix.

**Comment by angelozerr** [comment]
@janheyd-buchner your project is a Qute project?

**Comment by janheyd-buchner** [comment]
@angelozerr 

The issue seems to be fixed 🎉 

Thanks for your work! 😃
